[build]
  publish = "dist/proyecto-chat-bot/browser"
  command = "ng build --configuration=production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  OPENAI_API_KEY = "$OPENAI_API_KEY"
  OPENAI_ASSISTANT_ID = "$OPENAI_ASSISTANT_ID"